export {default as TabsContainer} from './tabs-container';
export {default as Settings} from './settings';
export {default as Registration} from './registration';
export {default as Profile} from './profile';
export {default as Login} from './login';
export {default as Preload} from './preload';
export {default as BackgroundContainer} from './background-container';
export {default as Events} from './events';
export {default as Favorits} from './favorits';
export {default as ForgotPassword} from './forgot-password';
export {default as Groups} from './groups';
export {default as Main} from './main';
export {default as PasswordApprove} from './password-approve';
export {default as PrivateChat} from './private-chat';
export {Contacts} from './contacts';
export {Messages} from './messages';
