export default {
  Contacts: 'Contacts',
  ContactAdd: 'ContactAdd',
  ContactProfile: 'ContactProfile',
  Events: 'Events',
  Favorites: 'Favorites',
  ForgotPassword: 'ForgotPassword',
  Groups: 'Groups',
  Login: 'Login',
  Messages: 'Messages',
  ChatCreate: 'ChatCreate',
  ChatMessage: 'ChatMessage',
  Preload: 'Preload',
  Registration: 'Registration',
  Settings: 'Settings',
  SoundSettings: 'SoundSettings',
  AppearanceSettings: 'AppearanceSettings',
  AdvancedSettings: 'AdvancedSettings',
  SafetySettings: 'SafetySettings',
  // modals
  RequestProfileModal: 'RequestProfileModal',
};
