export default {
  Registration: 'Registration',
  Login: 'Login',
  ForgotPassword: 'ForgotPassword',
  Main: 'Main',
  KeyImport: 'KeyImport',
  Contacts: 'Contacts',
  Preload: 'Preload',
  Events: 'Events',
  Messages: 'Messages',
  Groups: 'Groups',
  Settings: 'Settings',
  Favorits: 'Favorits',
  PasswordApprove: 'PasswordApprove',
  PrivateChat: 'PrivateChat',
  GroupChat: 'GroupChat',
};
