import React, {Component} from 'react';
import {PushNotificationIOS, AppState, Alert, DeviceInfo, Platform} from 'react-native';
import PushNotification from 'react-native-push-notification';
import {connect} from 'react-redux';
import PropTypes from 'prop-types';
import {isEmpty, map} from 'lodash';

import {MainLayout, BackgroundLayout} from '../../../components/layouts';
import {ChatList} from '../../../components/lists';
import {SearchInput, Navbar, NavbarDots, ButtonAdd, ChatListItem, ButtonNavbar} from '../../../components/elements';
import {chatActions, chatMessageActions, contactActions} from '../../../store/actions';
import {routeEnum} from '../../../enums';

const GET_ONLINE_UPDATE_TIME = 10000; // in ms

class Messages extends Component {

  static propTypes = {
    account: PropTypes.object,
    chat: PropTypes.object,
    chatMessage: PropTypes.object,
    contact: PropTypes.object,
    dispatch: PropTypes.func.isRequired,
    navigation: PropTypes.shape({navigate: PropTypes.func}),
  };

  static contextTypes = {
    t: PropTypes.func.isRequired,
  };

  state = {
    editMode: false,
    selected: {},
  };

  constructor(props) {
    super(props);
    this.timer = null;
  }

  componentDidMount() {
    this.init();
  }

  componentWillUnmount() {
    this.unmount();
  }

  init = () => {
    AppState.addEventListener('change', this.handleAppStateChange);
    this.pushNotificationConfigure();
    this.loadChatList();
    this.loadContactList();
    this.timer = setInterval(() => {
      this.props.dispatch(contactActions.getOnlineUsers());
    }, GET_ONLINE_UPDATE_TIME);
    // TODO - remove after tests
    // setTimeout(this.sendTestLocalNotification, 1000);
  };

  unmount = () => {
    clearInterval(this.timer);
    PushNotification.unregister();
    AppState.removeEventListener('change', this.handleAppStateChange);
  };

  handleAppStateChange = (state) => {
    console.log('APP STATE:', state);

    PushNotification.setApplicationIconBadgeNumber(0);

    if (state === 'active') {
    }
  };

  pushNotificationConfigure = () => {
    PushNotification.configure({
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: this.onPushRegister,

      onError: this.onPushRegistrationError,

      // (required) Called when a remote or local notification is opened or received
      onNotification: (notification) => {
        this.onPushNotification(notification);
        // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
        notification.finish(PushNotificationIOS.FetchResult.NoData);
      },

      // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
      senderID: 'YOUR GCM SENDER ID',

      // IOS ONLY (optional): default: all - Permissions to register.
      permissions: {
        alert: true,
        badge: true,
        sound: true
      },

      popInitialNotification: true,

      requestPermissions: true,
    });
  };

  onPushRegister = (token) => {
    console.log('TOKEN:', token);

    if (!token) {
      return;
    }

    let device = {
      uuid: DeviceInfo.getUniqueID(),
      type: Platform.OS,
      name: DeviceInfo.getModel(),
      token,
    };

    console.log('DEVICE:', device);
  };

  onPushRegistrationError = (error) => {
    console.log('NOTIFICATION ERROR:', error);

    if (!error) {
      return;
    }

    Alert.alert(
      'Failed To Register For Remote Push',
      `Error (${error.code}): ${error.message}`,
      [{
        text: 'Dismiss',
        onPress: null,
      }]
    );
  };

  onPushNotification = (notification) => {
    console.log('NOTIFICATION:', notification);

    if (!notification) {
      return;
    }

    const {message, data, badge} = notification;
    let onAlertPress = null;

    switch (notification.data.type) {
      default:
        break;
    }

    // TODO - remove after tests
    // Alert.alert('Local Push Notification', message);
  };

  sendTestLocalNotification = () => {
    PushNotification.localNotification({
      /* Android Only Properties */
      id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: 'My Notification Ticker', // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
      subText: 'This is a subText', // (optional) default: none
      color: 'red', // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: 'group', // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification

      /* iOS only properties */
      // alertAction: // (optional) default: view
      // category: // (optional) default: null
      // userInfo: // (optional) default: null (object containing additional notification data)

      /* iOS and Android properties */
      title: 'My Notification Title', // (optional)
      message: 'My Notification Message', // (required)
      playSound: true, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: 1, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      // repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
      // actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    });
  };

  loadContactList = (filter, sort, descending) => {
    return this.props.dispatch(contactActions.loadList(filter, sort, descending));
  };

  loadChatList = (filter, sort, descending) => {
    return this.props.dispatch(chatActions.loadList(filter, sort, descending));
  };

  createChat = async (contacts) => {
    return this.props.dispatch(chatActions.create(contacts));
  };

  updateChat = async (data) => {
    return this.props.dispatch(chatActions.update(data));
  };

  deleteChatById = async (id) => {
    return this.props.dispatch(chatActions.deleteById(id));
  };

  deleteChats = async (ids) => {
    return this.props.dispatch(chatActions.delete(ids));
  };

  loadChatMessages = () => {
    return this.props.dispatch(chatMessageActions.loadList());
  };

  sendChatMessage = ({data, chatId, timeDead}) => {
    return this.props.dispatch(chatMessageActions.send({data, chatId, timeDead}));
  };

  resendChatMessage = (id, timeDead) => {
    return this.props.dispatch(chatMessageActions.resend(id, timeDead));
  };

  editChatMessage = (data) => {
    return this.props.dispatch(chatMessageActions.edit(data));
  };

  deleteChatMessage = (id) => {
    return this.props.dispatch(chatMessageActions.delete(id));
  };

  searchChats = (text) => {
    const filter = `name CONTAINS[c] '${text}' OR shortName CONTAINS[c] '${text}' OR owner CONTAINS[c] '${text}'`;
    return this.loadChatList(filter);
  };

  onCreate = () => {
    this.props.navigation.navigate(routeEnum.ChatCreate);
  };

  onChatPress = (chat) => {
    if (this.state.editMode) {
      this.onChatCheckboxPress(chat);
      return;
    }

    this.props.navigation.navigate(routeEnum.ChatMessage, {chat});
  };

  onChatLongPress = (chat) => {
    if (!this.state.editMode) {
      this.setState({
        selected: {[chat.id]: chat},
        editMode: true,
      });
    }
  };

  onChatCheckboxPress = (chat) => {
    if (this.state.editMode) {
      const selected = {...this.state.selected};

      if (!selected[chat.id]) {
        selected[chat.id] = chat;
      } else {
        delete selected[chat.id];
      }

      if (isEmpty(selected)) {
        this.setState({
          editMode: false,
          selected: {},
        });
        return;
      }

      this.setState({selected});
    }
  };

  onChatsDelete = () => {
    const chatIds = map(this.state.selected, (item, key) => key);
    if (chatIds.length) {
      this.deleteChats(chatIds).then(() => {
        this.setState({
          editMode: false,
          selected: {},
        });
      });
    }
  };

  renderChatItem = ({item}) => {
    const {account} = this.props;

    return (
      <ChatListItem item={item}
                    theme={account.user.theme}
                    context={this.context}
                    editMode={this.state.editMode}
                    selectedItems={this.state.selected}
                    onPress={this.onChatPress}
                    onLongPress={this.onChatLongPress}
                    onCheckboxPress={this.onChatCheckboxPress}/>
    );
  };

  renderNavbarButton = () => {
    const {editMode} = this.state;

    if (editMode) {
      return (
        <ButtonNavbar position="right" onPress={this.onChatsDelete}>{this.context.t('Delete')}</ButtonNavbar>
      );
    }

    return <ButtonAdd onPress={this.onCreate}/>;
  };

  render() {
    const {account, chat} = this.props;
    const {theme} = account.user;

    return (
      <MainLayout netOffline={!account.net.connected} wsConnected={account.connected}>
        <BackgroundLayout theme={theme} paddingHorizontal={10}>
          <Navbar renderTitle={this.context.t('Messages')}
                  renderLeft={<NavbarDots/>}
                  renderRight={this.renderNavbarButton()}/>
          <SearchInput placeholder="Search in chats" onChange={this.searchChats}/>
          <ChatList theme={theme}
                    context={this.context}
                    items={chat.list}
                    renderItem={this.renderChatItem}/>
        </BackgroundLayout>
      </MainLayout>
    );
  }
}

export default connect(state => ({
  account: state.account,
  chat: state.chat,
  chatMessage: state.chatMessage,
  contact: state.contact,
}))(Messages);
